export const response = [
  {
    id: 'final-libertadores-2020',
    title: 'Libertadores',
    subtitle: 'Final 2020',
    categories: ['nacional'],
    location: 'Arena do Grêmio',
    date: '2020-08-08',
    img: '/images/final-libertadores-2020-capa-md.png',
    href: '/evento/final-libertadores-2020',
  },
  {
    id: 'open-rio-2021',
    title: 'Rio Open',
    subtitle: '2021',
    categories: ['nacional'],
    location: 'Arena do Grêmio',
    date: '2020-08-08',
    img: '/images/final-rio-open-2021-capa-md.png',
    href: '/evento/rio-open-2021',
  },
  {
    id: 'miami-open-2021',
    title: 'Miami Open',
    subtitle: '2021',
    categories: ['internacional'],
    location: 'Arena do Grêmio',
    date: '2020-08-08',
    img: '/images/capa-miami-open-2021-md.png',
    href: '/evento/miami-open-2021',
  },
  {
    id: 'mundial-de-clubes-2020',
    title: 'Mundial de Clubes',
    subtitle: '2020',
    categories: ['internacional'],
    location: 'Arena do Grêmio',
    date: '2020-08-08',
    img: '/images/mundial-de-clubes-2020-capa-md.png',
    href: '/evento/mundial-de-clubes-2020',
  },
  {
    id: 'final-champions-league-2021',
    title: 'Champions League',
    subtitle: 'Final 2021',
    categories: ['internacional'],
    location: 'Arena do Grêmio',
    date: '2020-08-08',
    img: '/images/final-champions-league-2021-md.png',
    href: '/evento/final-champions-league-2021',
  },
  {
    id: 'us-open-2021',
    title: 'Us Open',
    subtitle: '2021',
    categories: ['internacional'],
    location: 'Arena do Grêmio',
    date: '2020-08-08',
    img: '/images/us-open-2021-md.png',
    href: '/evento/us-open-2021',
  },
];
